// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYnpsQ8ZMSTZzZH99qfr1hkerup5fO4U',
    appId: '1:244393819335:web:da42f6107090c93a7c12e2',
    messagingSenderId: '244393819335',
    projectId: 'dahar-flutter-1e02e',
    authDomain: 'dahar-flutter-1e02e.firebaseapp.com',
    storageBucket: 'dahar-flutter-1e02e.firebasestorage.app',
    measurementId: 'G-SZFF1DRCN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09drpLhlMtvC_BuuG4ktCquCEnCcCzWQ',
    appId: '1:244393819335:android:3f131ca19c405e1c7c12e2',
    messagingSenderId: '244393819335',
    projectId: 'dahar-flutter-1e02e',
    storageBucket: 'dahar-flutter-1e02e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxP4roYlFSjtjLgVt83VHzhrFQAfsszRQ',
    appId: '1:244393819335:ios:7a393a8cd4d3154a7c12e2',
    messagingSenderId: '244393819335',
    projectId: 'dahar-flutter-1e02e',
    storageBucket: 'dahar-flutter-1e02e.firebasestorage.app',
    iosBundleId: 'com.example.dahar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFYnpsQ8ZMSTZzZH99qfr1hkerup5fO4U',
    appId: '1:244393819335:web:5f8c276c011306917c12e2',
    messagingSenderId: '244393819335',
    projectId: 'dahar-flutter-1e02e',
    authDomain: 'dahar-flutter-1e02e.firebaseapp.com',
    storageBucket: 'dahar-flutter-1e02e.firebasestorage.app',
    measurementId: 'G-FDBLXVTL6L',
  );
}
